name: depdendency auto upgrade format

env:
  CARGO_TERM_COLOR: always

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,18 * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ github.event.repository.name }}-${{ runner.os }}-dep-autoupgrade-v2
    - name: Install cargo-edit
      run: |
        [ ! -f ~/.cargo/bin/cargo-upgrade ] && \
        cargo install cargo-edit --features upgrade --bin cargo-upgrade
    - name: Run auto dependency update 
      uses: romoh/dependencies-autoupdate@v1
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: "~/.cargo/bin/cargo-upgrade --skip-compatible"
